### ISSUE TITLE
Upgrade to Python v3

### ISSUE THREAD

**Issue by confusedsecuritydudes** [confusedsecuritydudes/canaryemails#11]

**Comment by MonkeySec** [comment]
Created new feature branch 'p3dev' for Python v3 testing

**Comment by MonkeySec** [comment]
Converted canary.py and install-dbases.py to Python Version 3 in a new feature branch successfully using the "2to3" tool.

New files need to be tested.

**Comment by MonkeySec** [comment]
Completed conversion to Python 3, tested database creation scripts and all functions of canary script. Changes are in branch p3Dev ready for merging into Master.
